### ISSUE TITLE
not working all method in release mode

### ISSUE THREAD

**Issue by kamyar75** [jaumard/sms_autofill#103]
not working all method in release mode

04-01 00:43:39.333 14898-14939/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method listenForCode on channel sms_autofill)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
    <asynchronous suspension>
    #1      SmsAutoFill.listenForCode (package:sms_autofill/sms_autofill.dart:34)
    <asynchronous suspension>

**Comment by kamyar75** [comment]
how to solve this problem ???

**Comment by kevin997** [comment]
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

            minifyEnabled false
            shrinkResources false
        }
    }
    
    Try this in release mode

**Comment by jaumard** [comment]
Never got any issues in release mode... No sure what append, did you try to do a fresh clean of your project ?

**Comment by rajeshpatil95** [comment]
yes same here, Functionality not working in release mode but works in debug mode
"flutter build apk --release --flavor dev -t lib/main/main_dev.dart" try generating release build and test it...auto fill doesn't work

**Comment by prabuddaFernando** [comment]
I have same problem. ` await SmsAutoFill().hint` does not work at all

**Comment by omkarpatil1024** [comment]
the reason for it is app signature id is different for debug and release application. to find the app signature id for release app please run following command .Please find the solution for generating app signature Id flutter  run --release --dart-define=SMS_AUTOFILL_APP_SIGNATURE=<path/to/app-release.apk> for release application
