### ISSUE TITLE
Raising ERROR_START_SMS_RETRIEVER issue when navigating from Native Android/iOS to flutter side 

### ISSUE THREAD

**Issue by avaiyakirtib** [jaumard/sms_autofill#173]
ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(ERROR_START_SMS_RETRIEVER, Can't start sms retriever, null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
    <asynchronous suspension>
    #2      SmsAutoFill.listenForCode (package:sms_autofill/sms_autofill.dart:35:5)
    <asynchronous suspension>

**Comment by vanlooverenkoen** [comment]
We are having the same thing. Mostly samsung devices

**Comment by victortunts** [comment]
> We are having the same thing. Mostly samsung devices

Same here.

**Comment by AlmogAttal** [comment]
> We are having the same thing. Mostly samsung devices

Having the same issue with OnePlus, Asus, Samsung and Xiaomi

**Comment by arunkrishnakv** [comment]
Is someone working on this? Thanks.
