### ISSUE TITLE
Android 12 Crash

### ISSUE THREAD

**Issue by junaid1460** [jaumard/sms_autofill#179]
```
E/AndroidRuntime(28605): FATAL EXCEPTION: main
E/AndroidRuntime(28605): Process: com.mgoogle.android.gms:ui, PID: 28605
E/AndroidRuntime(28605): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mgoogle.android.gms/org.microg.gms.auth.credentials.CredentialPickerActivity}: java.lang.RuntimeException: createObject() requires a default constructor
E/AndroidRuntime(28605):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
E/AndroidRuntime(28605):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
E/AndroidRuntime(28605):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
E/AndroidRuntime(28605):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(28605):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(28605):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
E/AndroidRuntime(28605):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28605):        at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(28605):        at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(28605):        at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(28605):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28605):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(28605):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(28605): Caused by: java.lang.RuntimeException: createObject() requires a default constructor
E/AndroidRuntime(28605):        at org.microg.safeparcel.SafeParcelUtil.createObject(Unknown Source:43)
E/AndroidRuntime(28605):        at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(Unknown Source:2)
E/AndroidRuntime(28605):        at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(Unknown Source:0)
E/AndroidRuntime(28605):        at org.microg.gms.auth.credentials.CredentialPickerActivityKt.createFromBytes(Unknown Source:27)
E/AndroidRuntime(28605):        at org.microg.gms.auth.credentials.CredentialPickerActivity.onCreate(Unknown Source:87)
E/AndroidRuntime(28605):        at android.app.Activity.performCreate(Activity.java:8129)
E/AndroidRuntime(28605):        at android.app.Activity.performCreate(Activity.java:8109)
E/AndroidRuntime(28605):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
E/AndroidRuntime(28605):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
E/AndroidRuntime(28605):        ... 12 more
```

**Comment by junaid1460** [comment]
Device:
```
[1]: HD1901 (8b707042)
One plus 7T
```

**Comment by jaumard** [comment]
should be ok on 2.4.0
