### ISSUE TITLE
IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by lielvan** [jaumard/sms_autofill#214]
Getting the following exception reported by Crashlytics: 

Android Device version: Android 12
Plugin version: 2.3.0

```
  sms_autofill:
    dependency: "direct main"
    description:
      name: sms_autofill
      url: "https://pub.dev"
    source: hosted
    version: "2.3.0"
```

```
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at com.jaumard.smsautofill.SmsAutoFillPlugin$1.onActivityResult(SmsAutoFillPlugin.java:46)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:13)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchActivityResult(Activity.java:8385)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I deduced its related to this package from the following line:
`at com.jaumard.smsautofill.SmsAutoFillPlugin$1.onActivityResult(SmsAutoFillPlugin.java:46)`

Note, I haven't been able to reproduce the exception locally

**Comment by JayDropOn** [comment]
I got the same issue as well.

**Comment by PawanFyers** [comment]
@jaumard @grahamsmith @jack24254029  @pedromassango @asashour @knvpk @iamatulkumar :
Any update on the same ?

We have faced 100+ crashes on the same

`
Exception java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11012, result=0, data=Intent {  }} to activity {com.fyers.trader/com.fyers.fyers.MainActivity}: java.lang.IllegalStateException: Reply already submitted
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5658)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5697)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:67)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2465)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:240)
  at android.os.Looper.loop (Looper.java:351)
  at android.app.ActivityThread.main (ActivityThread.java:8370)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:568)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
Caused by java.lang.IllegalStateException: Reply already submitted
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:263)
  at com.jaumard.smsautofill.SmsAutoFillPlugin$1.onActivityResult (SmsAutoFillPlugin.java:68)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:813)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:432)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:868)
  at io.flutter.embedding.android.FlutterFragment.onActivityResult (FlutterFragment.java:1251)
  at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult (FlutterFragmentActivity.java:691)
  at android.app.Activity.dispatchActivityResult (Activity.java:8756)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5651)
`


```
sms_autofill:
    git:
      url: https://github.com/plavelo/sms_autofill.git
      ref: master
```

**Comment by RohitFyers** [comment]
Even I am facing this issue....

**Comment by pratikbaid3-curefit** [comment]
Facing the same issue. Any update on it?

**Comment by lokesh-univest** [comment]
Any update on this?

**Comment by AnirudhLoya** [comment]
Facing same crash issue, Any update?
