### ISSUE TITLE
crashes for android 14 

### ISSUE THREAD

**Issue by pranavpatel95** [jaumard/sms_autofill#217]
Fatal Exception: java.lang.SecurityException: com.getbitmoney.getbit: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
       at com.jaumard.smsautofill.SmsAutoFillPlugin$2.onSuccess(SmsAutoFillPlugin.java:44)
       at com.jaumard.smsautofill.SmsAutoFillPlugin$2.onSuccess(SmsAutoFillPlugin.java:2)
       at com.google.android.gms.tasks.zzm.run(zzm.java:25)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8194)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by qube-dev-tejas** [comment]
Hi @pranavpatel95 , did you get any solution ?

**Comment by pranavpatel95** [comment]
no  i didn't look for solutions, i dropped as a release was pending because of it.


Thanks & Regards

Pranav Patel
Junior Android Developer

Fermion Infotech Private Limited
CMMI Maturity Level 3, ISO 9001:2015, ISO/IEC 27001:2013, & ISO/IEC 20000-1:2018 certified
J-3032, Akshar Business Park, Plot No. 3 Sector 25, Vashi Koper Khairane Road, Vashi, Navi Mumbai-400703

Pune: 407 B Zen Business Center, Mumbai-Bangalore Express Highway, Shankar Kalat Nagar, Wakad, Pimpri-Chinchwad, Pune-411057

***@***.******@***.***> || www.fermioninfotech.com<http://www.fermioninfotech.com/>

________________________________

**Comment by JgomesAT** [comment]
I have the same error on Android 14, but not in other versions

**Comment by cekrozl1** [comment]
Same as https://github.com/jaumard/sms_autofill/issues/215

**Comment by Pursoth1815** [comment]
Use alt_sms_autofill Package for Read the Message for Android version 14.

***(********** NOTE *********************
and Add the below code in your Manifest file

<receiver
            android:name=".MyRadarReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="io.radar.sdk.RECEIVED" />
            </intent-filter>
        </receiver>

**Comment by jaumard** [comment]
should be ok on 2.4.0
