### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: 

### ISSUE THREAD

**Issue by user97116** [jaumard/sms_autofill#226]
```/AndroidRuntime( 8098): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/HintRequest$Builder;
E/AndroidRuntime( 8098): 	at com.jaumard.smsautofill.SmsAutoFillPlugin.requestHint(SmsAutoFillPlugin.java:161)
E/AndroidRuntime( 8098): 	at com.jaumard.smsautofill.SmsAutoFillPlugin.onMethodCall(SmsAutoFillPlugin.java:105)
E/AndroidRuntime( 8098): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime( 8098): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime( 8098): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 8098): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 8098): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8098): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8098): 	at android.os.Looper.loop(Looper.java:238)
E/AndroidRuntime( 8098): 	at android.app.ActivityThread.main(ActivityThread.java:7824)
E/AndroidRuntime( 8098): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8098): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.

**Comment by parthvirani-oceanmtech** [comment]
Has similar issue, is there any solution & my device was oneplus nord ce 3 lite with android version of 13

**Comment by DivyanshuKhattar** [comment]
Do you guys get any solution for this?

**Comment by sahilmehra98** [comment]
Check PR #232

**Comment by jaumard** [comment]
thanks to @sahilmehra98 should be ok on 2.4.0
