### ISSUE TITLE
App Crashing on Android 12 while fetching mobile hints

### ISSUE THREAD

**Issue by yogeshelevn** [jaumard/sms_autofill#228]
sms_authfill is encountering crashes specifically on the Android 12 version of the app when it tries to retrieve mobile hints. This leads to a fatal exception, which is then logged in the Firebase console.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, No Activity found to handle null, null, android.content.ActivityNotFoundException: No Activity found to handle null
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
	at android.app.Activity.startIntentSenderForResultInner(Activity.java:5670)
	at android.app.Activity.startIntentSenderForResult(Activity.java:5636)
	at android.app.Activity.startIntentSenderForResult(Activity.java:5603)
	at gf.b.h(Unknown Source:64)
	at gf.b.a(Unknown Source:66)
	at ig.j$a.a(Unknown Source:17)
	at xf.c.l(Unknown Source:18)
	at xf.c.m(Unknown Source:40)
	at xf.c.i(Unknown Source:0)
	at xf.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at SmsAutoFill.hint(sms_autofill.dart:30)
       at _LoginPageState.fetchMobileHints(login_page.dart:82)

**Comment by yogeshelevn** [comment]
@AryanBisht-03  No, I am also waiting for positive response here...

**Comment by Akhileshzoop** [comment]
@yogeshelevn Same buddy

**Comment by vidhi002** [comment]
did you find any solution?

**Comment by jaumard** [comment]
should be ok on 2.4.0
