### ISSUE TITLE
SmsAutoFill().hint not working. Not able to fetch the phone number. Pop-up gone as soon as it visible.

### ISSUE THREAD

**Issue by AryanBisht-03** [jaumard/sms_autofill#229]
Getting this error in Console:-

`E/ActivityThread( 7840):  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
`
In Android 14.

**Comment by mskyoindia** [comment]
I am also facing the same issue any solution for this ???
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Ubuntu 20.04.6 LTS 5.15.0-101-generic, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.89.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
FATAL EXCEPTION: main
                                                                                                    Process: des.dwgroup.app, PID: 8800
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/HintRequest$Builder;
                                                                                                    	at com.jaumard.smsautofill.SmsAutoFillPlugin.requestHint(SmsAutoFillPlugin.java:161)
                                                                                                    	at com.jaumard.smsautofill.SmsAutoFillPlugin.onMethodCall(SmsAutoFillPlugin.java:105)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.credentials.HintRequest$Builder" on path: DexPathList[[zip file "/data/app/~~6NjNBkU1Ql6qEtR5lUbKFA==/des.dwgroup.app-s-tlLTg3WoaiYSfpHQUnGA==/base.apk"],nativeLibraryDirectories=[/data/app/~~6NjNBkU1Ql6qEtR5lUbKFA==/des.dwgroup.app-s-tlLTg3WoaiYSfpHQUnGA==/lib/x86_64, /data/app/~~6NjNBkU1Ql6qEtR5lUbKFA==/des.dwgroup.app-s-tlLTg3WoaiYSfpHQUnGA==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by AryanBisht-03** [comment]
@mskyoindia did u find any solution ..?

**Comment by sahilmehra98** [comment]
Check PR #232

**Comment by jaumard** [comment]
thanks to @sahilmehra98 should be ok on 2.4.0
