### ISSUE TITLE
SmsAutoFill.hint  not open hint dialog

### ISSUE THREAD

**Issue by Vikash-mesky** [jaumard/sms_autofill#241]
Unhandled Exception: PlatformException(ERROR, 16: [28432] API has been disabled., com.google.android.gms.common.api.ApiException: 16: [28432] API has been disabled.

E/flutter (25511): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (25511): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (25511): <asynchronous suspension>
E/flutter (25511): #2      SmsAutoFill.hint (package:sms_autofill/sms_autofill.dart:33:28)
E/flutter (25511): <asynchronous suspension>
E/flutter (25511): #3      AuthLoginScreen.build.<anonymous closure> (package:ryder_app/modules/auth/view/ui/login_screen.dart:73:36)
E/flutter (25511): <asynchronous suspension>

**Comment by aneeshdevala** [comment]
in android its working for me

**Comment by CyberWake** [comment]
I to have faces this. It is mostly happening when the method channel call fails. In my case it failed due to the android device I used did not had a sim in it plus it was a new device provided I never got a sim card in it. Hence it failed to detect any phone number.
I have added a fix to this by adding a try catch block to consume any method channel failure calls within the library and return the fallback null result from hint getter.

**Comment by kushagragupta-baynine** [comment]
For me, it was disabled from settings.
You can enable by going to settings app ---> google--> default google account on device --> All services --> Phone number sharing --> Enable it.
you will see the bottom sheet with the number.
