### ISSUE TITLE
No phone number is found on this device., com.google.android.gms.common.api.ApiException

### ISSUE THREAD

**Issue by kamrujjamanjoy** [jaumard/sms_autofill#248]
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(ERROR, 16: [28438] No phone number is found on this device., com.google.android.gms.common.api.ApiException: 16: [28438] No phone number is found on this device.
E/flutter (31315): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.3.0:3)
E/flutter (31315): 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@18.3.0:4)
E/flutter (31315): 	at com.google.android.gms.internal.auth-api.zbao.zbb(com.google.android.gms:play-services-auth@@21.2.0:1)
E/flutter (31315): 	at com.google.android.gms.internal.auth-api.zbn.zba(com.google.android.gms:play-services-auth@@21.2.0:4)
E/flutter (31315): 	at com.google.android.gms.internal.auth-api.zbb.onTransact(com.google.android.gms:play-services-auth@@21.2.0:3)
E/flutter (31315): 	at android.os.Binder.execTransactInternal(Binder.java:1363)
E/flutter (31315): 	at android.os.Binder.execTransact(Binder.java:1304)
E/flutter (31315): , null)
E/flutter (31315): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:646:7)
E/flutter (31315): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (31315): <asynchronous suspension>
E/flutter (31315): #2      SmsAutoFill.hint (package:sms_autofill/sms_autofill.dart:33:28)
E/flutter (31315): <asynchronous suspension>
E/flutter (31315): #3      _PhoneFieldHintState._askPhoneHint (package:sms_autofill/sms_autofill.dart:393:20)
E/flutter (31315): <asynchronous suspension>
E/flutter (31315): #4      _PhoneFieldHintState.build.<anonymous closure> (package:sms_autofill/sms_autofill.dart:335:21)
E/flutter (31315): <asynchronous suspension>

**Comment by amit-iconflux** [comment]
I'm encountering this issue on a Samsung device with Android 14, although it works fine on other devices, including those with Android 14. This problem appears to be limited to Samsung's Android 14.

Tested device:

✅ POCO X4 (Android 13): Working
✅  Google Pixel 8 (Android 14): Working 
✅  Samsung M30 (Android 11): Working
✅  Samsung M31 (Android 12): Working 
✅  OnePlus 12R (Android 15): Working
✅  OnePlus Nord CE2 Lite (Android 14): Working
❌ Samsung S24 Ultra (Android 14): Not working
❌ Samsung A34 (Android 14): Not working 

@jaumard Can you please look in to this.

**Comment by hrajwade96** [comment]
Facing this issue in production app, for thousands of users, 
issue is not only for Samsung related devices but other brands as well.

logs 

[28438] No phone number is found on this device.
PlatformException
PlatformException(ERROR, 16: [28438] No phone number is found on this device., com.google.android.gms.common.api.ApiException: 16: [28438] No phone number is found on this device.
	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:14)
	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(Unknown Source:10)
	at com.google.android.gms.internal.auth-api.zbao.zbb(Unknown Source:2)
	at com.google.android.gms.internal.auth-api.zbn.zba(Unknown Source:22)
	at com.google.android.gms.internal.auth-api.zbb.onTransact(Unknown Source:20)
	at android.os.Binder.execTransactInternal(Binder.java:1220)
	at android.os.Binder.execTransact(Binder.java:1179)
, null)


Crashed in non-app: message_codecs.dart in StandardMethodCodec.decodeEnvelope within flutter

Show 2 more frames
sms_autofill.dart in SmsAutoFill.hint at line 33 within sms_autofill
In App
Called from: <asynchronous suspension>
login_mobile_input.dart in _MobileInputState._askPhoneHint at line 118 within

**Comment by hrajwade96** [comment]
this seems related to https://github.com/jaumard/sms_autofill/issues/241

for this there is a PR raised - https://github.com/jaumard/sms_autofill/pull/246

but this will just handle the exception, and not solve the underlying issue.

**Comment by anilac80** [comment]
I have tried in Samsung S21 FE (Android 15) getting same error. No phone number is found on this device.
