### ISSUE TITLE
Dialog does not close and when 2nd time tap on dialog then shutting down VM 

### ISSUE THREAD

**Issue by ShohidulProgrammer** [jaumard/sms_autofill#59]
I want to read my device phone number. When I tap on the icon button to call the _askPhoneHint() method then the dialog box does not close and also not read the phone number. When I tap next time then the app crashed.

here is my error report:

Shutting down VM
E/AndroidRuntime(25390): FATAL EXCEPTION: main
E/AndroidRuntime(25390): Process: com.it_home.chat_demo, PID: 25390
E/AndroidRuntime(25390): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11012, result=1001, data=Intent {  }} to activity {com.it_home.chat_demo/com.it_home.chat_demo.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25390): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4453)
E/AndroidRuntime(25390): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4495)
E/AndroidRuntime(25390): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(25390): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
E/AndroidRuntime(25390): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
E/AndroidRuntime(25390): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
E/AndroidRuntime(25390): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25390): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(25390): 	at android.app.ActivityThread.main(ActivityThread.java:6820)
E/AndroidRuntime(25390): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25390): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(25390): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
E/AndroidRuntime(25390): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25390): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(25390): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:235)
E/AndroidRuntime(25390): 	at com.jaumard.smsautofill.SmsAutoFillPlugin$1.onActivityResult(SmsAutoFillPlugin.java:65)
E/AndroidRuntime(25390): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(25390): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(25390): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(25390): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:584)
E/AndroidRuntime(25390): 	at android.app.Activity.dispatchActivityResult(Activity.java:7590)
E/AndroidRuntime(25390): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4446)
E/AndroidRuntime(25390): 	... 11 more

**Comment by praharshbhatt** [comment]
I face the same issue.
This is when the method is called multiple times in quick succession and needs to be handled from the native side.

[This](https://github.com/flutter/flutter/issues/29092) seems to be a related scenario.
